export type Values = Record<string, string | boolean | string[]>;
export type Widget = {
  id: string;
  eventId: string;
  kind: "Contacts" | "Links" | "Event Information";
  title: string;
  filter: Values;
  order: number;
};
export type EventRecord = {
  id: string;
  name: string;
  kind: "Event" | "Contact Store";
  startDate: string;
  endDate: string;
  durationEvidence: "observed" | "inferred";
  locationDisplay: string;
  venue: string;
  city: string;
  state: string;
  country: string;
  uniqueCode: string;
  alias: string;
  timeZone: string;
  currency: string;
  favorite: boolean;
  archived: boolean;
  seedOrder: number;
  contactStoreId: string;
  modules: string[];
  preferences: Values;
  widgets: Widget[];
};
export type Contact = {
  id: string;
  eventId: string;
  createdDate: string;
  firstName: string;
  lastName: string;
  organization: string;
  position: string;
  street: string;
  city: string;
  state: string;
  country: string;
  postcode: string;
  email: string;
  photoStatus: string;
  photoDate?: string;
  nextAction?: string;
  externalId?: string;
  dietaryRequirements: string[];
  dietaryUpdatedDate?: string;
  bio?: string;
  inactive: boolean;
  inactiveDate?: string;
  incomplete: boolean;
  incompleteDate?: string;
  incompleteSite?: string;
  checkedIn: boolean;
  checkInDate?: string;
  badgePrinted: boolean;
  marketingPrivacy: string;
  processingConsent: string;
  visibility: string;
  trackingIncomplete?: string;
  trackingSubmitted?: string;
};
export type Sort = { field: string; direction: "asc" | "desc" } | null;
export type Store = {
  version: 1;
  events: EventRecord[];
  sort: Sort;
  presets: Record<string, Values>;
  askHelp: boolean;
  recents: string[];
};
